---
language: python
services: docker

env:
  matrix:
    - MOLECULE_DISTRO: centos:7
    - MOLECULE_DISTRO: centos:6
    - MOLECULE_DISTRO: amazonlinux:1
    - MOLECULE_DISTRO: amazonlinux:2
    - MOLECULE_DISTRO: debian:8
    - MOLECULE_DISTRO: debian:9
    - MOLECULE_DISTRO: ubuntu:16.04
    - MOLECULE_DISTRO: ubuntu:18.04

install:
  - pip install molecule docker

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
