---
- block:
  - name: Install Percona repository (RedHat)
    yum:
      name: "{{ percona_repo_url }}"
      state: present

  - name: Import the Percona RPM GPG key
    rpm_key:
      key: "{{ percona_repo_gpg_key_url }}"
      state: present
  when: ansible_os_family == "RedHat"

- name: Install Percona repository (Debian)
  apt:
    deb: "{{ percona_repo_url }}"
    force_apt_get: true
  when: ansible_os_family == "Debian"
